project_name: helm-subenv
builds:
  - binary: ./bin/subenv
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64

archives:
  - id: tar
    format: tar.gz
    files:
      - LICENSE
      - plugin.yaml