name: "subenv"
version: "0.0.12"
usage: "Substitutes the values of environment variables."
description: |-
  The plugin allows to substitue the values of environment variables withing a CICD pipeline.
useTunnel: true
command: "bin/subenv"
hooks:
  install: "$HELM_PLUGIN_DIR/subenv.sh"
  update: "$HELM_PLUGIN_DIR/subenv.sh"