name: "subenv"
version: "0.1.0"
usage: "Substitutes the values of environment variables."
description: |-
  The plugin allows to substitue the values of environment variables withing a CICD pipeline.
command: "$HELM_PLUGIN_DIR/bin/subenv"
hooks:
  install: "$HELM_PLUGIN_DIR/subenv.sh"
  update: "$HELM_PLUGIN_DIR/subenv.sh"